// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqMUtr7Q3auyd609y-SAisfL2XnYkv9KM',
    appId: '1:2403693966:web:9f478988cdce3ab5ae60df',
    messagingSenderId: '2403693966',
    projectId: 'crime-lens-d8706',
    authDomain: 'crime-lens-d8706.firebaseapp.com',
    storageBucket: 'crime-lens-d8706.firebasestorage.app',
    measurementId: 'G-YTWDCJ56BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoA_oXIaxpqA45uXjwK3U6hljPp_cBjNI',
    appId: '1:2403693966:android:4b59570d7f3673b7ae60df',
    messagingSenderId: '2403693966',
    projectId: 'crime-lens-d8706',
    storageBucket: 'crime-lens-d8706.firebasestorage.app',
  );
}
